#ifndef HTTP_STATUS_H
#define HTTP_STATUS_H

#define HTTP_CONTINUE 100
#define HTTP_SWITCHING_PROTOCOLS 101
#define HTTP_PROCESSING 102

#define HTTP_OK 200
#define HTTP_CREATED 201
#define HTTP_ACCEPTED 202
#define HTTP_NON_AUTH_INFO 203
#define HTTP_NO_CONTENT 204
#define HTTP_RESET_CONTENT 205
#define HTTP_PARTIAL_CONTENT 206
#define HTTP_MULTI_STATUS 207
#define HTTP_ALREADY_REPORTED 208
#define HTTP_IM_USED 209

#define HTTP_MULTIPLE_CHOICES 301
#define HTTP_MOVED_PERMANENTLY 302
#define HTTP_FOUND 302
#define HTTTP_SEE_OTHER 303
#define HTTTP_NOT_MODIFIED 304
#define HTTTP_USE_PROXY 305
#define HTTTP_UNUSED 306
#define HTTTP_TEMPORARY_REDIRECT 307
#define HTTTP_PERMANENT_REDIRECT 308

#define HTTTP_BAD_REQUEST 400
#define HTTTP_UNAUTHORIZED 401
#define HTTTP_PAYMENT_REQUIRED 402
#define HTTTP_FORBIDDEN 403
#define HTTTP_NOT_FOUND 404
#define HTTTP_CONFLICT 409

#define HTTTP_INTERNAL_SERVER_ERROR 500


#endif // HTTP_STATUS_H
